# Stage 1: Base image
FROM node:18-alpine AS base

WORKDIR /usr/src/app

# Install dependencies
COPY backend/package*.json ./
RUN npm install --production

# Copy app source
COPY backend/ ./

# Expose port
EXPOSE 5000

# Start command
CMD [ "node", "src/index.js" ]